export const THEME_COLORS = {
    light: {
        mainBackgroundColor: '#fafcfa',
        loginBackgroundColorRight: '#5fa15f',
        loginBackgroundColorLeft: '#369f36',
        loginWindowBorder: 'rgba(8,168,8,0.53)',
        textColor: '#2d2b2b',
        lightTextColor: '#f7faf7',
        accentTextColor: '#32CD32FF',
        headerBackgroundColor: '#454b45',
        headerTextColor: '#FFFFFFFF',
        cardColor: '#fbfffb',
        cardBorderColor: 'rgba(8,168,8,0.22)',
        buttonColor: '#32CD32FF',
        buttonHoverColor: '#5DD75DFF',
        buttonHoverShadow: '#abb7ab',
        inputBorderColor: '#ced0ca',
        partBackgroundColor: '#eef8ee',
        descriptionPartColor: '#d8e0d8',
    },
    dark: {
        mainBackgroundColor: '#596759',
        loginBackgroundColorRight: '#738f73',
        loginBackgroundColorLeft: '#143a14',
        loginWindowBorder: '#026E0287',
        textColor: '#e7e6e6',
        lightTextColor: '#e5e8e5',
        accentTextColor: '#32CD32FF',
        headerBackgroundColor: '#303a30',
        headerTextColor: '#FFFFFFFF',
        cardColor: '#5C755CFF',
        cardBorderColor: '#455945FF',
        buttonColor: '#63BD63FF',
        buttonHoverColor: '#5F985FFF',
        buttonHoverShadow: '#50b250',
        inputBorderColor: '#d5d9d3',
        partBackgroundColor: '#465d46',
        descriptionPartColor: '#3a3d3a',
    },
}

