export const THEME_COLORS = {
    light: {
        mainBackgroundColor: '#fafcfa',
        loginBackgroundColorRight: '#5fa15f',
        loginBackgroundColorLeft: '#369f36',
        loginWindowBorder: 'rgba(8,168,8,0.53)',
        textColor: '#2d2b2b',
        lightTextColor: '#f7faf7',
        accentTextColor: '#32CD32FF',
        headerBackgroundColor: '#454b45',
        headerTextColor: '#FFFFFFFF',
        cardColor: '#fbfffb',
        // cardColor: '#e3ffe3',
        cardBorderColor: '#d0fdd0',
        buttonColor: '#32CD32FF',
        buttonHoverColor: '#5DD75DFF',
        buttonHoverShadow: '#abb7ab',
        inputBorderColor: '#ced0ca',
        partBackgroundColor: '#d4fdd4',
    },
    dark: {
        mainBackgroundColor: '#596759',
        loginBackgroundColorRight: '#5fa15f',
        loginBackgroundColorLeft: '#369f36',
        loginWindowBorder: '#026E0287',
        textColor: '#e7e6e6',
        lightTextColor: '#e5e8e5',
        accentTextColor: '#32CD32FF',
        headerBackgroundColor: '#303a30',
        headerTextColor: '#FFFFFFFF',
        cardColor: '#5C755CFF',
        cardBorderColor: '#455945FF',
        buttonColor: '#63BD63FF',
        buttonHoverColor: '#5F985FFF',
        buttonHoverShadow: '#4c914c',
        inputBorderColor: '#d5d9d3',
        partBackgroundColor: '#455945FF',
    },
}

