export const THEME_COLORS = {
    light: {
        mainBackgroundColor: '#fafcfa',
        loginBackgroundColorRight: '#5fa15f',
        loginBackgroundColorLeft: '#369f36',
        loginWindowBackground: '#fafcfa',
        loginWindowBorder: 'rgba(8,168,8,0.53)',
        loginWindowTextColor: '#2d2b2b',
        textColor: '#2d2b2b',
        lightTextColor: '#f7faf7',
        accentTextColor: '#5fa15f',
        headerBackgroundColor: '#475447',
        headerTextColor: '#FFFFFF',
        cardColor: '#fbfffb',
        cardTextColor: '#2d2b2b',
        cardBorderColor: '#C8E6C9',
        buttonColor: '#32CD32FF',
        buttonHoverColor: '#59d959',
        buttonHoverShadow: '#abb7ab',
        inputBorderColor: '#C8E6C9',
        inputTextColor: '#2d2b2b',
        partBackgroundColor: '#edf6ed',
        descriptionPartColor: '#C8E6C9',
        rejectButtonColor: '#757575',
        rejectHoverButtonColor: '#757575',
    },
    dark: {
        mainBackgroundColor: '#739173',
        loginBackgroundColorRight: '#738f73',
        loginBackgroundColorLeft: '#143a14',
        loginWindowBackground: '#8da98d',
        loginWindowBorder: '#738f73',
        loginWindowTextColor: '#2d2b2b',
        textColor: '#cdcecc',
        lightTextColor: '#e5e8e5',
        accentTextColor: '#388E3C',
        headerBackgroundColor: '#303a30',
        headerTextColor: '#FFFFFFFF',
        cardColor: '#8da98d',
        cardTextColor: '#2d2b2b',
        cardBorderColor: '#5c795c',
        buttonColor: '#388E3C',
        buttonHoverColor: '#4CAF50',
        buttonHoverShadow: '#325232',
        inputBorderColor: '#738f73',
        inputTextColor: '#FFFFFFFF',
        partBackgroundColor: '#5C755CFF',
        descriptionPartColor: '#485248',
        rejectButtonColor: '#757575',
        rejectHoverButtonColor: '#757575',
    },
};

